### ISSUE TITLE
Seems to be broken

### ISSUE THREAD

**Issue by SheepCommander** [Neppkun/tnylnk-powercord#1]
![image](https://user-images.githubusercontent.com/66646514/148759541-017e737f-9f32-46d8-8935-e067f41367ec.png)

![image](https://user-images.githubusercontent.com/66646514/148759537-bc03b38d-d6cc-4765-b7e3-c1f06897beeb.png)

```diff
VM952 C:\Users\zachi\powercord\src\Powercord\plugins\pc-commands\monkeypatchMessages.js:32 An error occurred while executing command tnylnk: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at shorteneris (C:\Users\zachi\powercord\src\Powercord\plugins\tnylnk-powercord\index.js:23:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.messages.sendMessage.oldSendMessage [as sendMessage] (C:\Users\zachi\powercord\src\Powercord\plugins\pc-commands\monkeypatchMessages.js:25:16)
```

**Comment by SheepCommander** [comment]
Aight!
